# Generated by Django 4.1.2 on 2022-12-31 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0012_auto_20200827_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='category',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
